doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: false
        mappings:
            User:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Infrastructure/Entity'
                prefix: 'App\User\Infrastructure\Entity'
                alias: User
            Measurement:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Measurement/Infrastructure/Entity'
                prefix: 'App\Measurement\Infrastructure\Entity'
                alias: Measurement
            MeasurementHistory:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Measurement/Infrastructure/Entity'
                prefix: 'App\Measurement\Infrastructure\Entity'
                alias: MeasurementHistory
