framework:
    messenger:
        transports:
            async:
                dsn: '%env(RABBITMQ_DSN)%'
                options:
                    exchange:
                        name: messages
                        type: direct
                    queues:
                        messages: ~
        routing:
            'App\Training\Domain\Event\Workout\WorkoutCreatedEvent': async
            'App\Training\Domain\Event\Workout\WorkoutDeletedEvent': async
