version: '3.8'

services:
  # PHP-FPM service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-container
    volumes:
      - /home/jakub/Pulpit/TrainingApp/App:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - app-network
    depends_on:
      - db

  # Nginx service
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - /home/jakub/Pulpit/TrainingApp/App:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - php

  # MySQL database service
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: db
      PMA_USER: symfony_user
      PMA_PASSWORD: symfony_password
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app-network


volumes:
  db-data:

networks:
  app-network:
    driver: bridge
